### PR TITLE
Fix W^X policy for apple portability

### PR DESCRIPTION
**Pull request by jtgrassie**
`pthread_jit_write_protect_np` undefined on at least Mojave (10.14.6, x86_64).

### CODE REVIEW

**Comment by hyc** [comment]
@selsta tested the current code successfully on x86-64 already. If this is not working on Macos 10, then the ifdef should be against the OS version, not the CPU type. And if we need a single binary to work on multiple OS revisions, then we need a runtime check for this function's usability.

The patch in this PR should not be accepted as-is.

**Comment by jtgrassie** [comment]
> @selsta tested the current code successfully on x86-64 already.

But did he test o earlier versions of macOS (i.e. before macOS 11 Big Sur)?

**Comment by jtgrassie** [comment]
> IMO we should probably drop support for MacOS 10. 

Last macOS 10 (10.15) was released end of 2019, which is fairly recent.

**Comment by selsta** [comment]
We cross compile with the 10.11 SDK in gitian / depends and I did not see any build failure yet.

So I'm surprised that it fails on 10.14

**Comment by jtgrassie** [comment]
@selsta Monero build output against 10.15 SDK:

```
[ 40%] Building CXX object external/randomx/CMakeFiles/randomx.dir/src/virtual_memory.cpp.o
/Users/dog/monero/external/randomx/src/virtual_memory.cpp:118:2: error: use of undeclared identifier 'pthread_jit_write_protect_np'
        pthread_jit_write_protect_np(false);
        ^
/Users/dog/monero/external/randomx/src/virtual_memory.cpp:138:2: error: use of undeclared identifier 'pthread_jit_write_protect_np'
        pthread_jit_write_protect_np(false);
        ^
/Users/dog/monero/external/randomx/src/virtual_memory.cpp:146:2: error: use of undeclared identifier 'pthread_jit_write_protect_np'
        pthread_jit_write_protect_np(true);
```

**Comment by selsta** [comment]
With this patch `MAP_JIT` doesn't get set anymore on x86-64 so that has to be changed.

**Comment by selsta** [comment]
An `ifdef` for the OS version (11 or newer) would be fine too. I think not using `pthread_jit_write_protect_np` on older Intel Macs shouldn't matter.

**Comment by jtgrassie** [comment]
> An ifdef for the OS version (11 or newer) would be fine too. I think not using pthread_jit_write_protect_np on older Intel Macs shouldn't matter.

Which goes back to @hyc's point:

>> And if we need a single binary to work on multiple OS revisions, then we need a runtime check for this function's usability.

As it stands, this patch allows to build for target ARM **or** X86_64. If we want to a single binary that will work on _both_, we need runtime checks for `pthread_jit_write_protect_np`. I can rework with the runtime checks if desired, the only reason I didn't add was because of the unknown overhead.

**Comment by jtgrassie** [comment]
@selsta df45079 with runtime checking.

**Comment by selsta** [comment]
> If we want to a single binary that will work on both, we need runtime checks for pthread_jit_write_protect_np

Can you explain why? We can use `lipo` to combine an Intel binary compiled with 10.11 SDK and an ARM binary compiled with 11 SDK. No runtime checks required, but maybe I'm missing something.

**Comment by jtgrassie** [comment]
> Can you explain why?

It's not really an architecture issue but rather an SDK issue. `pthread_jit_write_protect_np` simply doesn't exist on < MacOS 11, hence the undefined errors.

**Comment by selsta** [comment]
> pthread_jit_write_protect_np simply doesn't exist on < MacOS 11

That's why I suggested to simply ifdef for the macOS version. Basically your current patch without the `__builtin_available ` runtime check. But like I said, maybe I'm missing something.

**Comment by jtgrassie** [comment]
The `__builtin_available` is for the _runtime_ checks. Hence this will run on 10 and 11.

**Comment by selsta** [comment]
do you need `AvailabilityMacros.h`?

**Comment by selsta** [comment]
and I still don't understand why you need a runtime check but I will let @hyc review this

**Comment by selsta** [comment]
The weird thing is CI compiles RandomX 1.1.10 under macOS 10.15 without any build errors:

https://github.com/monero-project/monero/runs/4144066544?check_suite_focus=true

**Comment by jtgrassie** [comment]
> and I still don't understand why you need a runtime check

My understanding is that `pthread_jit_write_protect_np` is only _implemented_ on apple silicon. So you could be running on 11 but not ARM. I don't have an apple silicon machine to test (though your lipo suggestion should also work), but without this patch, it's not possible to even compile or run on < 11.

**Comment by jtgrassie** [comment]
> The weird thing is CI compiles RandomX 1.1.10 under macOS 10.15 without any build errors

Because it's using `MacOSX11.1.sdk`.

**Comment by selsta** [comment]
>Because it's using MacOSX11.1.sdk.

True, seems Github updates Xcode in the VM image. Only question remaining is why cross compiling still worked with the 10.11 SDK.

**Comment by jtgrassie** [comment]
> Only question remaining for me is why cross compiling still worked with the 10.11 SDK

It only "worked" insofar as it compiled something that won't run on 10.x.

File: src/virtual_memory.cpp [hunk 1]
```diff
@@ -134,16 +138,22 @@ static inline void pageProtect(void* ptr, std::size_t bytes, int rules) {
 }
 
 void setPagesRW(void* ptr, std::size_t bytes) {
-#ifdef USE_PTHREAD_JIT_WP
-	pthread_jit_write_protect_np(false);
+#if defined(USE_PTHREAD_JIT_WP) && defined(MAC_OS_VERSION_11_0) \
+	&& MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_VERSION_11_0
+	if (__builtin_available(macOS 11.0, *)) {
+		pthread_jit_write_protect_np(false);
+	}
```
Comment (hyc) [inline src/virtual_memory.cpp:145]: This is a no-op if `pthread_jit_write_protect_np` is not available. If it's not available it should be using `pageProtect`.

That was the entire point of issue #216. Let's not run around in circles here.

**Comment by hyc** [comment]
> > Only question remaining for me is why cross compiling still worked with the 10.11 SDK
> 
> It only "worked" insofar as it compiled something that won't run on 10.x.

Still, it should not have linked successfully then, when built with the 10.x SDK. Something still doesn't make sense here.

**Comment by jtgrassie** [comment]
> Still, it should not have linked successfully then, when built with the 10.x SDK. Something still doesn't make sense here.

It wasn't built with the 10.x SDK. It won't build with the 10.x SDK. That's the what started me down this rabbit hole.

**Comment by selsta** [comment]
gitian cross compiling was built with the 10.11 SDK.

https://github.com/monero-project/monero/runs/4144066674?check_suite_focus=true

**Comment by jtgrassie** [comment]
> gitian cross compiling was built with the 10.11 SDK.
> 
> https://github.com/monero-project/monero/runs/4144066674?check_suite_focus=true

That is a different matter (gitian), because `pthread_jit_write_protect_np` _does not exist_ on 10.x. This must mean `USE_PTHREAD_JIT_WP` is not getting defined in that gitian build (if it was, you'd get an undefined on `pthread_jit_write_protect_np`). 

If you want to build on 10 or 11 to create a single binary that can run on 10 & 11 (using `pthread_jit_write_protect_np` when available), you need this PR.

**Comment by hyc** [comment]
I've run this patch on my M1 Macbook Pro with no apparent impact on randomx-benchmark performance or correctness. LGTM.

**Review by hyc — APPROVED** [review]

**Comment by hyc** [comment]
Final thought - if there is no performance gain on x86 for using `pthread_jit_write_protect_np` then maybe we should just go back to the earlier commit where it was only used on aarch64.

**Comment by selsta** [comment]
> Final thought - if there is no performance gain on x86 for using pthread_jit_write_protect_np then maybe we should just go back to the earlier commit where it was only used on aarch64.

Might be the easiest solution, yes.

**Comment by jtgrassie** [comment]
> Final thought - if there is no performance gain on x86 for using `pthread_jit_write_protect_np` then maybe we should just go back to the earlier commit where it was only used on aarch64.

Well, this has all the compile _and_ runtime checks now, so is more portable.

**Review by selsta — APPROVED** [review]
Tested on:

- Intel 10.12.6, 10.15.7, 11.6.1
- ARM 12.1
