### ISSUE TITLE
Cross compile on Ubuntu 18.04 fails targetting Windows

### ISSUE THREAD

**Issue by ipbc-dev** [tevador/RandomX#184]
```
/external/randomx/src/tests/benchmark.cpp:45:10: fatal error: VersionHelpers.h: No such file or directory
#include <VersionHelpers.h>
```

In Ubuntu 18.04 (and maybe other distros) the package for the cross compile has this header but named `versionhelpers.h` (lowercase).

Manually editing benchmark.cpp and setting lowercase header name causes compile to go forward and complete successfully.

**Comment by tevador** [comment]
Patched. Thanks.

**Comment by ipbc-dev** [comment]
-- Please reply above this line --


Hello!

We received your request and will get in touch with you as soon as
possible.

We usually reply WITHIN 24 HOURS BETWEEN MONDAY TO FRIDAY.

In the meantime, you can have a look at the BitTube Knowledge Base:
https://kb.bittubeapp.com [1] and reply to this email with 'SOLVED',
if you found the answer to your question.

Thanks for your understanding.

Talk to you soon,

Your BitTube Team.


Links:
------
[1] https://kb.bittubeapp.com
